Csv bug co 372
Sunbird-coKreat/program-service pull request #300
Opened 2023-03-23 13:51 UTC by rekhaLuezoid

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Nodejs 8.11.2
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-24 14:09 UTC, vinukumar-vs requested changes

2023-03-24 14:09 UTC, vinukumar-vs commented on src/service/print/csv.js
> +    Option1: questionOptions.length > 0 ? questionOptions[0][0] : "",
I would suggest to use for loop instead of manualy coding for each option

2023-03-24 14:09 UTC, vinukumar-vs commented on src/service/print/csv.js
> +    Option1: questionOptions.length > 0 ? questionOptions[0][0] : "",
Use for loop for number of options & append the key(option+i) to the "data" object.

2023-03-24 14:52 UTC, vinukumar-vs commented
Also follow the git commit format

Issue #CO-XXXX fix: {commit message}
https://udacity.github.io/git-styleguide/

2023-03-31 09:45 UTC, pallakartheekreddy approved these changes

2023-03-31 09:45 UTC, merged